//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Iso58Entities : DbContext
    {
        public Iso58Entities()
            : base("name=Iso58Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DataDictionary> DataDictionary { get; set; }
        public virtual DbSet<DataDictionaryItems> DataDictionaryItems { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<Function> Function { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Order> Order { get; set; }
    
        public virtual ObjectResult<sp_perf_stats_azure_Result> sp_perf_stats_azure(string appname, Nullable<System.DateTime> runtime)
        {
            var appnameParameter = appname != null ?
                new ObjectParameter("appname", appname) :
                new ObjectParameter("appname", typeof(string));
    
            var runtimeParameter = runtime.HasValue ?
                new ObjectParameter("runtime", runtime) :
                new ObjectParameter("runtime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_perf_stats_azure_Result>("sp_perf_stats_azure", appnameParameter, runtimeParameter);
        }
    
        public virtual ObjectResult<sp_perf_stats_azure_infrequent11_Result> sp_perf_stats_azure_infrequent11(Nullable<System.DateTime> runtime, Nullable<int> firstrun)
        {
            var runtimeParameter = runtime.HasValue ?
                new ObjectParameter("runtime", runtime) :
                new ObjectParameter("runtime", typeof(System.DateTime));
    
            var firstrunParameter = firstrun.HasValue ?
                new ObjectParameter("firstrun", firstrun) :
                new ObjectParameter("firstrun", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_perf_stats_azure_infrequent11_Result>("sp_perf_stats_azure_infrequent11", runtimeParameter, firstrunParameter);
        }
    }
}
