//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Order = new HashSet<Order>();
        }
    
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CorporationName { get; set; }
        public string Status { get; set; }
        public string Industry { get; set; }
        public long DepartmentID { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string City { get; set; }
        public string MobileTel { get; set; }
        public string SourseFrom { get; set; }
        public string CustomerType { get; set; }
        public Nullable<System.DateTime> NextContactTime { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
        public string Province { get; set; }
        public Nullable<double> RegisteredCapital { get; set; }
        public string Address { get; set; }
        public string WebSite { get; set; }
        public string WebSiteRemark { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public long Owner { get; set; }
        public Nullable<System.DateTime> FirstContactDate { get; set; }
        public string FirstRemark { get; set; }
        public Nullable<System.DateTime> SecondContactDate { get; set; }
        public string SecondRemark { get; set; }
        public Nullable<System.DateTime> ThirdContactDate { get; set; }
        public string ThirdRemark { get; set; }
        public Nullable<System.DateTime> FourthContactDate { get; set; }
        public string FourthRemark { get; set; }
        public Nullable<System.DateTime> FifthContactDate { get; set; }
        public string FifthRemark { get; set; }
        public Nullable<System.DateTime> SixthContactDate { get; set; }
        public string SixthRemark { get; set; }
        public Nullable<System.DateTime> SeventhContactDate { get; set; }
        public string SeventhRemark { get; set; }
        public Nullable<System.DateTime> EighthContactDate { get; set; }
        public string EighthRemark { get; set; }
        public Nullable<System.DateTime> NinthContactDate { get; set; }
        public string NinthRemark { get; set; }
        public Nullable<System.DateTime> TenthContactDate { get; set; }
        public string TenthRemark { get; set; }
        public Nullable<short> PoolStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ElevenContactDate { get; set; }
        public string ElevenRemark { get; set; }
        public Nullable<System.DateTime> twelveContactDate { get; set; }
        public string twelveRemark { get; set; }
        public Nullable<System.DateTime> thirteenContactDate { get; set; }
        public string thirteenRemark { get; set; }
        public Nullable<System.DateTime> fourteenContactDate { get; set; }
        public string fourteenRemark { get; set; }
        public Nullable<System.DateTime> fifteenContactDate { get; set; }
        public string fifteenRemark { get; set; }
        public Nullable<System.DateTime> sixteenContactDate { get; set; }
        public string sixteenRemark { get; set; }
        public Nullable<System.DateTime> seventeenContactDate { get; set; }
        public string seventeenRemark { get; set; }
        public Nullable<System.DateTime> eighteenContactDate { get; set; }
        public string eighteenRemark { get; set; }
        public Nullable<System.DateTime> nineteenContactDate { get; set; }
        public string nineteenRemark { get; set; }
        public Nullable<System.DateTime> twentyContactDate { get; set; }
        public string twentyRemark { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> BelongDateTime { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
