//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Customer = new HashSet<Customer>();
            this.User = new HashSet<User>();
        }
    
        public long DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string MANAGER { get; set; }
        public string DEPDESCRIPTION { get; set; }
        public long FACTORYID { get; set; }
        public Nullable<long> PARENTDEPID { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
