//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public Factory()
        {
            this.Department = new HashSet<Department>();
        }
    
        public long C_FACTORYID { get; set; }
        public string C_FactoryName { get; set; }
        public string C_FACTORYDES { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual ICollection<Department> Department { get; set; }
    }
}
