//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        public Function()
        {
            this.Permission = new HashSet<Permission>();
        }
    
        public long PURVIEWID { get; set; }
        public string FuncationCode { get; set; }
        public long MenuID { get; set; }
        public Nullable<int> ORDERQTY { get; set; }
        public string FUNCTIONNAME { get; set; }
        public string TOOLTIPTEXT { get; set; }
        public string FunctionImages { get; set; }
        public Nullable<System.DateTime> TR { get; set; }
    
        public virtual ICollection<Permission> Permission { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
