//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Period { get; set; }
        public string Keyword { get; set; }
        public string KeywordAttach { get; set; }
        public string Url { get; set; }
        public string IDCode { get; set; }
        public string TemplateCode { get; set; }
        public string Idea { get; set; }
        public string BaiduAccount { get; set; }
        public string BaiduPwd { get; set; }
        public string BaiduAnswer { get; set; }
        public string OrderRemark { get; set; }
        public string ContractCode { get; set; }
        public string ContractMoney { get; set; }
        public string ContractRealArrival { get; set; }
        public string ContractModifyfee { get; set; }
        public string CheckStatus { get; set; }
        public string Product { get; set; }
        public string OnlineEngine { get; set; }
        public string PauseEngine { get; set; }
        public string ShopStatus { get; set; }
        public string ShopAddress { get; set; }
        public string FollowUpPerson { get; set; }
        public Nullable<System.DateTime> ShopMakeStarttime { get; set; }
        public Nullable<System.DateTime> ShopMakeEndtime { get; set; }
        public string ShopRemark { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> GuideStarttime { get; set; }
        public Nullable<System.DateTime> GuideEndtime { get; set; }
        public Nullable<System.DateTime> NuggetStarttime { get; set; }
        public Nullable<System.DateTime> NuggetEndtime { get; set; }
        public string OperationRemark { get; set; }
        public string CustomerStatus { get; set; }
        public long CustomerId { get; set; }
        public long UserId { get; set; }
        public string SignBill { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
