//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Permission = new HashSet<Permission>();
            this.User = new HashSet<User>();
        }
    
        public long ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> TR { get; set; }
    
        public virtual ICollection<Permission> Permission { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
