//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public long USERID { get; set; }
        public long ROLEID { get; set; }
        public string USERNAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public long DEPARTMENTID { get; set; }
        public Nullable<byte> USERTYPE { get; set; }
        public Nullable<bool> USERSTATE { get; set; }
        public string MOBILEPHONE { get; set; }
        public Nullable<System.DateTime> TR { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
    }
}
